# Dockerfile.backup
FROM ubuntu:latest

# Install MySQL client
RUN apt-get update && \
    apt-get install -y mysql-client && \
    rm -rf /var/lib/apt/lists/*

# Copy backup script into the container
COPY backup.sh /backup.sh

# Copy scheduling script into the container
COPY run_backup.sh /run_backup.sh

# Make scripts executable
RUN chmod +x /backup.sh /run_backup.sh

# Define entry point for the container
ENTRYPOINT ["/run_backup.sh"]
